export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_CATEGORIES : "SET_CATEGORIES",
    ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART" ,
    SET_CART : "SET_CART",
  };